print("Hola mundo".upper())
print("Hola mundo".lower())
print("hola mundo".capitalize())
print("hola mundo".title())
print("Hola mundo mundo mundo".count("mundo"))
print("Hola mundo mundo".find('mundo'))
print("Hola mundo mundo mundo".rfind('mundo'))
print("125".isdigit())
print("125asd45".isalnum())
print("adfasdf".isalpha())
print("hola".islower())
print("HOLA".islower())
print("HOLA".istitle())
print("  ".isspace())
print("Hola Mundo".startswith("Hola"))
print("Hola Mundo".endswith("Mundo"))
print("Hola*mundo".split("*"))
print("-".join("Hola mundo"))
print("    Hola mundo  ".strip())
print("Hola mundo".replace("0","0"))